import Head from 'next/head';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { useQuery } from 'react-query';
import {
  Box,
  Button,
  Flex,
  Heading,
  Input,
  Spinner,
  Text,
} from '@chakra-ui/react';

import { fetchMoviesAndSeries } from '@/utils/fetch';

import MovieList from '@/components/MovieList';

import styles from '@/styles/Home.module.css';

export default function Home() {
  const [searchValue, setSearchValue] = useState('');

  const { isLoading, isError, data, error } = useQuery(
    ['moviesAndSeries', searchValue],
    () => fetchMoviesAndSeries(searchValue)
  );

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();

  const onSubmit = formData => setSearchValue(formData.searchValue);

  if (isError) {
    return <span>Error: {error.message}</span>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Series and Movie Watch List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading as="h1" size="3xl" mb={6}>
          Series and Movie Watch List
        </Heading>

        <Box mb={6}>
          <Flex as="form" onSubmit={handleSubmit(onSubmit)}>
            <Flex mr={2} flexDir="column">
              <Input
                placeholder="Star Wars"
                type="text"
                {...register('searchValue', { required: true })}
              />
              {errors.searchValue && (
                <Text fontSize="md" color="red.500">
                  This field is required
                </Text>
              )}
            </Flex>
            <Button
              colorScheme="blue"
              type="submit"
              isLoading={isLoading}
              loadingText="Searching"
              spinnerPlacement="end"
            >
              Search
            </Button>
          </Flex>
        </Box>

        {isLoading && (
          <Flex alignItems="center" h="md">
            <Spinner
              thickness="4px"
              speed="0.65s"
              emptyColor="gray.200"
              color="blue.500"
              size="xl"
            />
          </Flex>
        )}

        {data && (
          <div>
            <MovieList movies={data} />
          </div>
        )}
      </main>
    </div>
  );
}
