import Head from 'next/head';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { useQuery } from 'react-query';

import { fetchMoviesAndSeries } from '@/utils/fetch';

import styles from '@/styles/Home.module.css';
import MovieList from '@/components/MovieList';

export default function Home() {
  const [searchValue, setSearchValue] = useState('');

  const { isLoading, isError, data, error } = useQuery(
    ['moviesAndSeries', searchValue],
    () => fetchMoviesAndSeries(searchValue)
  );

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();

  const onSubmit = formData => setSearchValue(formData.searchValue);

  if (isLoading) {
    return <span>Loading...</span>;
  }

  if (isError) {
    return <span>Error: {error.message}</span>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Series and Movie Watch List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Series and Movie Watch List</h1>

        <div>
          <form onSubmit={handleSubmit(onSubmit)}>
            <input
              type="text"
              {...register('searchValue', { required: true })}
            />
            {errors.searchValue && <span>This field is required</span>}
            <input type="submit" value="Search" />
          </form>
        </div>

        {data && (
          <div>
            <MovieList movies={data} />
          </div>
        )}
      </main>
    </div>
  );
}
