import Head from "next/head";
import { useState } from "react";
import { useQuery } from "react-query";
import { Flex, Heading, Spinner } from "@chakra-ui/react";

import { fetchMoviesAndSeries } from "@/utils/fetch";

import MovieList from "@/components/MovieList";
import SearchForm from "@/components/SearchForm";

import styles from "@/styles/Home.module.scss";

const isServer = typeof window === "undefined";

export default function Home() {
  const [searchValue, setSearchValue] = useState(
    (!isServer && localStorage.getItem("searchValue")) || "",
  );

  const { isLoading, isError, data, error } = useQuery(
    ["moviesAndSeries", searchValue],
    () => fetchMoviesAndSeries(searchValue),
  );

  if (isError) {
    return <span>Error: {error.message}</span>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Series and Movie Watch List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading as="h1" size="3xl" mb={6}>
          Series and Movie Watch List
        </Heading>

        <SearchForm
          searchValue={searchValue}
          setSearchValue={setSearchValue}
          isLoading={isLoading}
        />

        {isLoading && (
          <Flex alignItems="center" h="md">
            <Spinner
              thickness="4px"
              speed="0.65s"
              emptyColor="gray.200"
              color="blue.500"
              size="xl"
            />
          </Flex>
        )}

        {data && (
          <div>
            <MovieList movies={data} />
          </div>
        )}
      </main>
    </div>
  );
}
